-- Einmal im Supabase SQL Editor ausführen.
create table if not exists public.redemptions (
  id bigint generated by default as identity primary key,
  identifier_hash text not null unique,
  identifier_type text not null check (identifier_type in ('ausweis', 'andere_angabe')),
  created_at timestamptz not null default now()
);

-- Die Website greift ausschließlich über die Vercel-API mit dem Service-Role-Key zu.
-- Darum bleiben direkte Zugriffe für anonyme und eingeloggte Nutzer gesperrt.
alter table public.redemptions enable row level security;
